apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helmchart
  namespace: argocd
spec:
  project: default
  
  source:
    helm:
      valueFiles:
        - values-uat.yaml
    path: mongo-app-helmchart 
    repoURL: https://github.com/stwalez/devops-acceler8-task-k8s
    targetRevision: HEAD
  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: uat
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
