apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-helmchart-ns
  namespace: argocd
spec:
  project: default
  source:
    chart: mongo-app-helmchart
    repoURL: https://github.com/stwalez/devops-acceler8-task-k8s.git
    targetRevision: 0.1.2
    helm:
      releaseName: mongo-app-helmchart
      valueFiles:
        - values-uat.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: uat

