apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stwalez/devops-acceler8-task-k8s.git
    targetRevision: HEAD
    path: mongo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true