# Default values for mongo-app-helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

envName: dev


dbImage:
  name: mongodb
  repository: mongo
  containerPort: 27017
  servicePort: 27017

expressImage:
  name: mongo-express
  image: mongo-express
  containerPort: 8081
  servicePort: 8081
  nodePort: 30000

secret:
  username: bW9uZ29hZG1pbg==
  password: bW9uZ29wYXNzd29yZA==

replicaCount: 1

