apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret-{{ .Values.envName }}
type: Opaque
data:
    mongo-root-username: {{ .Values.secret.username }}
    mongo-root-password: {{ .Values.secret.password }}