apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-{{ .Values.envName }}
spec:
  selector:
    app: mongodb-{{ .Values.envName }}
  ports:
    - protocol: TCP
      port: {{ .Values.dbImage.servicePort }}
      targetPort: {{ .Values.dbImage.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express-{{ .Values.envName }}
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{ .Values.expressImage.servicePort }}
      targetPort: {{ .Values.expressImage.containerPort }}
      nodePort: {{ .Values.expressImage.nodePort }}